project_id = "jyldgwtaoieiibtwqqlm"

[functions.login-attempts]
verify_jwt = false

[functions.setup-2fa]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false
